version: '3.5'

services:
    mongo:
        container_name: thx_mongo
        image: mongo
        env_file: .env
        restart: always
        ports:
            - 27018:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: admin
        volumes:
            - mongo-data:/data/db
            - ./fixture/db:/docker-entrypoint-initdb.d/fixture
            - ./scripts/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh

    hardhat:
        container_name: thx_hardhat
        image: public.ecr.aws/o5j5y3t5/hardhat-thx-artifacts:4.0.4
        domainname: hardhat.thx.local
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        ports:
            - 8547:8545
        expose:
            - 8545
        environment:
            - VIRTUAL_HOST=hardhat.thx.local
            - VIRTUAL_PORT=8545

    nginx:
        image: nginx:1.17.10
        container_name: thx_nginx
        depends_on:
            - hardhat
        volumes:
            - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./certs/localhost.key:/etc/nginx/certs/nginx.key
            - ./certs/localhost.crt:/etc/nginx/certs/nginx.crt
        ports:
            - 8546:443

volumes:
    mongo-data:
