name: E2E Tests

# on:
#     schedule:
#         - cron: '0 10 * * *'
on: [push]

jobs:
    e2e:
        name: 'E2E'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Chrome latest
              uses: browser-actions/setup-chrome@latest
              run: echo "BROWSER_PATH=$(which chrome)" >> $GITHUB_ENV

            - name: Chrome E2E Test ðŸš€
              uses: cypress-io/github-action@v4
              with:
                  install: true
                  record: true
                  browser: '${{ env.BROWSER_PATH }}'
                  start: yarn test:e2e
              env:
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
